[versions]
micronaut-docs = "2.0.0"
micronaut = "4.4.0"
micronaut-test = "4.1.1"
activemq = '5.18.3'
amazon-sqs-messaging = '2.0.3'
micronaut-platform = "4.2.3"
artemis-client = '2.31.2'
awaitility = '4.2.0'
commons-pool2 = '2.12.0'
graal-svm = "23.1.2"
groovy = "4.0.17"
json-api = '1.1.4'
jcl-slf4j = '2.0.12'
jms-api = '2.0.1'
jsr305 = "3.0.2"
kotlin = '1.9.24'
spock = "2.3-groovy-4.0"
spotbugs = "4.8.3"
micronaut-validation = "4.4.0"
micronaut-aws = "4.4.1"
micronaut-gradle-plugin = "4.3.5"
micronaut-logging = "1.1.2"

[libraries]
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
micronaut-aws = { module = "io.micronaut.aws:micronaut-aws-bom", version.ref = "micronaut-aws" }
activemq-broker = { module = 'org.apache.activemq:activemq-broker', version.ref = 'activemq' }
activemq-client = { module = 'org.apache.activemq:activemq-client', version.ref = 'activemq' }
amazon-sqs-messaging = { module = 'com.amazonaws:amazon-sqs-java-messaging-lib', version.ref = 'amazon-sqs-messaging' }
artemis-client = { module = 'org.apache.activemq:artemis-jms-client', version.ref = 'artemis-client' }
awaitility = { module = 'org.awaitility:awaitility', version.ref = 'awaitility' }
aws-sqs = { module = 'software.amazon.awssdk:sqs'}
commons-pool2 = { module = 'org.apache.commons:commons-pool2', version.ref = 'commons-pool2' }
graal-svm = { module = "org.graalvm.nativeimage:svm", version.ref = "graal-svm" }
jcl-slf4j = { module = 'org.slf4j:jcl-over-slf4j', version.ref = 'jcl-slf4j' }
jms-api = { module = 'javax.jms:javax.jms-api', version.ref = 'jms-api' }
jsr305 = {group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
spotbugs = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }
javax-json-api = { module = 'javax.json:javax.json-api', version.ref = 'json-api' }

#plugins

micronaut-gradle-plugin = { module = 'io.micronaut.gradle:micronaut-gradle-plugin', version.ref = 'micronaut-gradle-plugin' }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kotlin-allopen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
